name = "hermes"
description = "Minimalistic blog theme"
min_version = "0.20.0"
license = "MIT"
homepage = "https://github.com/janmasrovira/hermes"
demo = "TODO"

[extra]

[author]
name = "janmasrovira"
homepage = "https://github.com/janmasrovira"
